"""add CASCADE question_id

Revision ID: 4581e4ae0004
Revises: cc5d7a81febd
Create Date: 2025-09-13 22:22:20.487399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4581e4ae0004'
down_revision: Union[str, None] = 'cc5d7a81febd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('question_categories_question_id_fkey', 'question_categories', type_='foreignkey')
    op.drop_constraint('question_categories_category_id_fkey', 'question_categories', type_='foreignkey')
    op.create_foreign_key(None, 'question_categories', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'question_categories', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question_categories', type_='foreignkey')
    op.drop_constraint(None, 'question_categories', type_='foreignkey')
    op.create_foreign_key('question_categories_category_id_fkey', 'question_categories', 'categories', ['category_id'], ['id'])
    op.create_foreign_key('question_categories_question_id_fkey', 'question_categories', 'questions', ['question_id'], ['id'])
    # ### end Alembic commands ###
